### ISSUE TITLE
Breadcumbs struggle with local classes

### ISSUE THREAD

**Issue by Geolykt** [Col-E/recaf-3x-issues#110]
Exception stacktrace:
```
18:43:51.009 [GuiPresentation/JavaFX Application Thread] ERROR: Uncaught exception on thread 'JavaFX Application Thread'
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "name" is null
	at me.coley.recaf.ui.control.tree.OutlineTree.filter(OutlineTree.java:118)
	at me.coley.recaf.ui.control.tree.OutlineTree.lambda$getItems$3(OutlineTree.java:103)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at me.coley.recaf.ui.control.tree.OutlineTree.getItems(OutlineTree.java:110)
	at me.coley.recaf.ui.control.tree.OutlineTree.onUpdate(OutlineTree.java:76)
	at me.coley.recaf.ui.pane.outline.OutlinePane.onUpdate(OutlinePane.java:145)
	at me.coley.recaf.ui.ClassView.onUpdate(ClassView.java:107)
	at me.coley.recaf.ui.ClassView.<init>(ClassView.java:65)
	at me.coley.recaf.ui.CommonUX.lambda$openClass$0(CommonUX.java:47)
	at me.coley.recaf.ui.docking.RecafDockingManager.decorateFactory(RecafDockingManager.java:113)
	at me.coley.recaf.ui.docking.DockingManager.createTab(DockingManager.java:82)
	at me.coley.recaf.ui.CommonUX.openClass(CommonUX.java:46)
	at me.coley.recaf.ui.control.tree.WorkspaceTree.openItem(WorkspaceTree.java:57)
	at me.coley.recaf.ui.control.tree.WorkspaceCell.onMouseClick(WorkspaceCell.java:56)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3586)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

InnerClasses attribute of outer class:
```
InnerClasses:
  #15 of #2;                              // class snoddasmannen/galimulator/localclass_3 of class snoddasmannen/galimulator/Alliance
  #17 of #2;                              // class snoddasmannen/galimulator/localclass_4 of class snoddasmannen/galimulator/Alliance
  #19 of #2;                              // class snoddasmannen/galimulator/localclass_5 of class snoddasmannen/galimulator/Alliance
  #21 of #2;                              // class snoddasmannen/galimulator/localclass_6 of class snoddasmannen/galimulator/Alliance
  #23 of #2;                              // class snoddasmannen/galimulator/localclass_8 of class snoddasmannen/galimulator/Alliance
  #25 of #2;                              // class snoddasmannen/galimulator/localclass_10 of class snoddasmannen/galimulator/Alliance
  #28= #27 of #2;                         // Local0=class snoddasmannen/galimulator/Alliance$Local0 of class snoddasmannen/galimulator/Alliance
  public static final #33= #30 of #32;    // BuiltinSymbols=class snoddasmannen/galimulator/FlagItem$BuiltinSymbols of class snoddasmannen/galimulator/FlagItem
```
InnerClasses attribute of inner class (snoddasmannen/galimulator/Alliance$Local0):
```
InnerClasses:
  #8= #2 of #7;                           // Local0=class snoddasmannen/galimulator/Alliance$Local0 of class snoddasmannen/galimulator/Alliance
```
InnerClasses attribute of another inner class (snoddasmannen/galimulator/localclass_4):
```InnerClasses:
  #2 of #7;                               // class snoddasmannen/galimulator/localclass_4 of class snoddasmannen/galimulator/Alliance
EnclosingMethod: #7.#10                 // snoddasmannen.galimulator.Alliance.getItems
```

(sidenote: I feel that the classes with the `localclass_X` naming scheme cause the issue. The two different naming schemes are caused by the fact that I am using two different algorithms to enumerate local classes - one can only detect THAT they are local classes, the other is also able to detect their out method/class)

I unfortunately cannot give a sample as that sample is ARR.

Tagging @Amejonah1200 since they authored affected subsystems

**Comment by Col-E** [comment]
Addressed by https://github.com/Col-E/Recaf/pull/601
