### ISSUE TITLE
Stackoverflow error with latest update

### ISSUE THREAD

**Issue by sureshg** [Col-E/recaf-3x-issues#117]
* Env
```bash
recaf: 3.0.0-SNAPSHOT-15
 ❯ java --version
openjdk 17.0.4 2022-07-19 LTS
OpenJDK Runtime Environment Zulu17.36+13-CA (build 17.0.4+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.36+13-CA (build 17.0.4+8-LTS, mixed mode, sharing)
```
* Error

```
08:22:32.742 [Lang/main] WARN : Tried to set translations to 'en_US', but no entries for the translations were found!
08:22:32.742 [Lang/main] WARN : Tried to set translations to 'en_US', but no entries for the translations were found!
08:22:32.742 [Lang/main] WARN : Tried to set translations to 'en_US', but no entries for the translations were found!
08:22:32.742 [Lang/main] WARN : Tried to set translations to 'en_US', but no entries for the translations were found!
08:22:32.742 [Lang/main] WARN : Tried to set translations to 'en_US', but no entries for the translations were found!
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:106)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:280)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.warn(Logger.java:704)
	at me.coley.recaf.util.logging.InterceptingLogger.warn(InterceptingLogger.java:278)
	at me.coley.recaf.util.logging.InterceptingLogger.warn(InterceptingLogger.java:268)
	at me.coley.recaf.ui.util.Lang.setCurrentTranslations(Lang.java:67)
	at me.coley.recaf.ui.util.Lang.setCurrentTranslations(Lang.java:69)
	at me.coley.recaf.ui.util.Lang.setCurrentTranslations(Lang.java:69)
```

**Comment by Col-E** [comment]
Maybe for some reason the way we introspect to find translation files is failing? 

Added additional logging to check for this: https://github.com/Col-E/Recaf/commit/352ccbedd4586777d5535f173d9a6d37bb4bb528

**Comment by sureshg** [comment]
```
09:08:50.627 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
09:08:50.636 [JFXInjection/main] INFO : Checking local cache for JavaFX dependencies...
09:08:50.639 [JFXInjection/main] INFO : JavaFX classpath injection complete
09:08:50.651 [Lang/main] ERROR: Translations could not be loaded! CodeSource: file:/Users/xxxx/install/tools/recaf
09:08:50.651 [Lang/main] WARN : Tried to set translations to 'en_US', but no entries for the translations were found!
09:08:50.651 [Lang/main] ERROR: Could not load default translations: en_US
09:08:50.685 [ConfigRegistry/main] DEBUG: Register config container: conf.display
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "map" is null
	at me.coley.recaf.ui.util.Lang.get(Lang.java:265)
	at me.coley.recaf.ui.util.Lang.get(Lang.java:252)
	at me.coley.recaf.config.ConfigRegistry.getFieldDisplay(ConfigRegistry.java:223)
	at me.coley.recaf.config.ConfigRegistry.register(ConfigRegistry.java:99)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at me.coley.recaf.presentation.GuiPresentation.initialize(GuiPresentation.java:41)
	at me.coley.recaf.Recaf.initialize(Recaf.java:38)
	at me.coley.recaf.Main.main(Main.java:44)
```

**Comment by sureshg** [comment]
Not sure why is it looking for translations in the current working directory `Translations could not be loaded! CodeSource: file:/Users/xxxx/install/tools/recaf`? Is that expected?

**Comment by Col-E** [comment]
`CodeSource: file:/Users/xxxx/install/tools/recaf`

That is... odd. Are you using `java -jar <recaf-jar-here>` to launch it?

**Comment by sureshg** [comment]
No, using this really executable jar stub. This was working fine with older releases though 

```
cat stub.sh
#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"

EXEC=$(basename "$0")
SELF="$DIR/$EXEC"

exec java -jar "$SELF" "$@"
exit 1
```

```
$ cat stub.sh recaf-3.0.0-SNAPSHOT-J11-jar-with-dependencies.jar > recaf
$ chmod +x recaf
$./recaf
```

**Comment by sureshg** [comment]
by the way `java -jar ....` is working fine 👍🏼

**Comment by Col-E** [comment]
I'm not so sure I understand what the bash script accomplishes. At the end it still seems to run `java -jar <path>`, which should mean the target jar is still the same, right?

**Comment by tth05** [comment]
Looks like the code source become the bash script file instead of the jar file it's running. I'd say that's probably the fault of the script instead of recaf.

**Comment by sureshg** [comment]
> bash script file instead of the jar file it's running. I'd say that's probably the fault of the script instead of recaf.

Yeah, but jvm can load and run those script prepended jar files without any issues. Even maven plugins like `really executable jar` does the same trick.

**Comment by sureshg** [comment]
Anyway, thanks for looking into the issue.
