### ISSUE TITLE
Throwing an exception when opening a jar package

### ISSUE THREAD

**Issue by meiMingle** [Col-E/recaf-3x-issues#142]
> 10:20:20.621 [SsvmIntegration/Recaf SSVM-0] ERROR: SSVM failed to initialize
java.lang.IllegalStateException: VM bootstrap failed
        at dev.xdark.ssvm.VirtualMachine.bootstrap(VirtualMachine.java:288)
        at me.coley.recaf.ssvm.IntegratedVirtualMachine.bootstrap(IntegratedVirtualMachine.java:69)
        at me.coley.recaf.ssvm.SsvmIntegration.lambda$updatePrimaryVm$0(SsvmIntegration.java:62)
        at me.coley.recaf.ssvm.SsvmIntegration.createVM(SsvmIntegration.java:116)
        at me.coley.recaf.ssvm.SsvmIntegration.updatePrimaryVm(SsvmIntegration.java:60)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Uncaught VM error at: java/lang/System.initPhase1()V
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.VirtualMachine.bootstrap(VirtualMachine.java:258)
        ... 9 common frames omitted
Caused by: java.lang.IllegalStateException: Uncaught VM error at: java/lang/System.newPrintStream(Ljava/io/FileOutputStream;Ljava/lang/String;)Ljava/io/PrintStream;
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:36)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:19)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 11 common frames omitted
Caused by: java.lang.IllegalStateException: Uncaught VM error at: java/io/PrintStream.<init>(Ljava/io/OutputStream;ZLjava/lang/String;)V
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:36)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:19)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 17 common frames omitted
Caused by: java.lang.IllegalStateException: Uncaught VM error at: java/io/PrintStream.<init>(Ljava/io/OutputStream;ZLjava/nio/charset/Charset;)V
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:36)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:19)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 23 common frames omitted
Caused by: java.lang.IllegalStateException: Uncaught VM error at: java/io/OutputStreamWriter.<init>(Ljava/io/OutputStream;Ljava/nio/charset/Charset;)V
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:36)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:19)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 29 common frames omitted
Caused by: java.lang.IllegalStateException: Uncaught VM error at: sun/nio/cs/StreamEncoder.forOutputStreamWriter(Ljava/io/OutputStream;Ljava/lang/Object;Ljava/nio/charset/Charset;)Lsun/nio/cs/StreamEncoder;
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:36)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:19)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 35 common frames omitted
Caused by: java.lang.IllegalStateException: Uncaught VM error at: sun/nio/cs/StreamEncoder.<init>(Ljava/io/OutputStream;Ljava/lang/Object;Ljava/nio/charset/Charset;)V
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:36)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:19)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 41 common frames omitted
Caused by: java.lang.IllegalStateException: Uncaught VM error at: sun/nio/cs/MS936.newEncoder()Ljava/nio/charset/CharsetEncoder;
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:36)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:19)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 47 common frames omitted
Caused by: java.lang.IllegalStateException: Uncaught VM error at: sun/nio/cs/MS936.initc2b()V
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:76)
        at dev.xdark.ssvm.util.VMHelper.invoke(VMHelper.java:78)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:36)
        at dev.xdark.ssvm.execution.rewrite.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:19)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 53 common frames omitted
Caused by: java.lang.ClassCastException: class dev.xdark.ssvm.value.SimpleArrayValue cannot be cast to class dev.xdark.ssvm.value.InstanceValue (dev.xdark.ssvm.value.SimpleArrayValue and dev.xdark.ssvm.value.InstanceValue are in unnamed module of loader 'app')
        at dev.xdark.ssvm.util.VMOperations.monitorExit(VMOperations.java:1213)
        at dev.xdark.ssvm.execution.SimpleExecutionContext.monitorExit(SimpleExecutionContext.java:121)
        at dev.xdark.ssvm.execution.asm.MonitorExitProcessor.execute(MonitorExitProcessor.java:17)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:59)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:25)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:66)
        ... 59 common frames omitted

**Comment by Col-E** [comment]
> ERROR: SSVM failed to initialize

SSVM (https://github.com/xxDark/SSVM) is an optional component in 3X. If it does not initialize Recaf operates normally, but SSVM integrations are disabled. You can ignore this message.
