### ISSUE TITLE
classes not shown & jphantom crash due to invalid class name

### ISSUE THREAD

**Issue by Janmm14** [Col-E/recaf-3x-issues#147]
No classes in _ dir are shown at all in recaf
```
java.lang.IllegalArgumentException: Invalid class name (must be an internal class name): //\/ဈ‮//$$2985
	at org.objectweb.asm.util.CheckMethodAdapter.checkInternalClassName(CheckMethodAdapter.java:1333)
	at org.objectweb.asm.util.CheckMethodAdapter.checkInternalName(CheckMethodAdapter.java:1311)
	at org.objectweb.asm.util.CheckClassAdapter.visit(CheckClassAdapter.java:233)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
	at org.clyze.jphantom.methods.MethodLookupTable$CachingAdapter.visit(MethodLookupTable.java:79)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
	at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
	at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
	at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
	at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
	at org.clyze.jphantom.adapters.MethodAdder.visit(MethodAdder.java:52)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
	at org.clyze.jphantom.adapters.SuperclassAdapter.visit(SuperclassAdapter.java:27)
	at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:123)
	at org.clyze.jphantom.adapters.InterfaceAdder.visit(InterfaceAdder.java:30)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.clyze.jphantom.Transformer.transform(Transformer.java:53)
	at org.clyze.jphantom.Phantoms.generateClasses(Phantoms.java:57)
	at org.clyze.jphantom.JPhantom.run(JPhantom.java:116)
	at me.coley.recaf.util.JPhantomUtil.generate(JPhantomUtil.java:76)
	at me.coley.recaf.util.CompileDependencyUpdater.createPhantoms(CompileDependencyUpdater.java:55)
	at me.coley.recaf.util.CompileDependencyUpdater.lambda$install$0(CompileDependencyUpdater.java:37)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalArgumentException: Invalid null (must not contain . ; [ or /): //\/ဈ‮//$$2985
	at org.objectweb.asm.util.CheckMethodAdapter.checkIdentifier(CheckMethodAdapter.java:1248)
	at org.objectweb.asm.util.CheckMethodAdapter.checkInternalClassName(CheckMethodAdapter.java:1328)
	... 31 more
```
Sample from https://github.com/NaulbiMIX/EaZy-Client

**Comment by Col-E** [comment]
If you disable JPhantom in the config does the issue about classes not being shown go away?

**Comment by Janmm14** [comment]
I have to correct myself, the directory is not `_` it is an empty directory. After disabling Config -> Compiler -> Generate missing classes, the error went away, but the classes are still not shown.

**Comment by Col-E** [comment]
![image](https://github.com/Col-E/recaf-3x-issues/assets/21371686/0a419b68-0229-461a-b209-2eee047bf918)
![image](https://github.com/Col-E/recaf-3x-issues/assets/21371686/8a8e0bd5-4588-4dd5-945b-b138d8196f59)


So, they are indeed classes. However, they do not end in a `.class` suffix. So they aren't gonna be loaded in a normal way, I would say could be subject to putting them under files instead of classes on that technicality. Anyways, in 3x these items are skipped since we skip `//` and `../` zip entry paths.

I can remove the check since we're fully in memory and such things don't really affect us.

**Comment by Janmm14** [comment]
They *do* end in .class, its just shown wrong in your screen due to Right-to-Left-character

**Comment by Col-E** [comment]
![image](https://github.com/Col-E/recaf-3x-issues/assets/21371686/ab8889b5-e3b2-4369-bcb8-17e091c34172)

This is the solution I'm going to work with for now in 4x. As much as I'm not a fan of the parent package directory being the _"root"_ visually, thats what the path denotes.

**Comment by Col-E** [comment]
Closing as addressed in 4x, which is where effort is being put into currently.
