### ISSUE TITLE
error in run program

### ISSUE THREAD

**Issue by sami-soft** [Col-E/recaf-3x-issues#150]
```
java -jar recaf-3.0.0-SNAPSHOT-J11-jar-with-dependencies.jar
23:57:22.839 [Main/main] TRACE: Compressing 0 old log files
23:57:22.970 [Recaf/main] DEBUG: Initialize: Recaf-3.0.0-SNAPSHOT (50d3bece93e1dafb05f9c4f7ca31e35f64fa88aa) - 2023 03/31 23:39
23:57:22.973 [Recaf/main] DEBUG: java.home = C:\Program Files\Java\jdk-20
23:57:22.974 [Recaf/main] DEBUG: java.version = 20.0.1
23:57:22.974 [Recaf/main] DEBUG: java.vm.vendor = Oracle Corporation
23:57:22.974 [Recaf/main] DEBUG: java.vm.version = 20.0.1+9-29
23:57:22.974 [Recaf/main] DEBUG: os.arch = amd64
23:57:22.974 [Recaf/main] DEBUG: os.bitness = 64
23:57:22.975 [Recaf/main] DEBUG: os.name = Windows 10
23:57:22.975 [Recaf/main] DEBUG: os.processors = 8
23:57:22.975 [Recaf/main] DEBUG: os.version = 10.0
23:57:23.145 [AccessPatcher/main] DEBUG: Opening access to all packages
23:57:23.183 [AccessPatcher/main] DEBUG: Patching package reflection restrictions
23:57:23.201 [JFXInjection/main] INFO : Checking local cache for JavaFX dependencies...
23:57:23.212 [JFXInjection/main] INFO : JavaFX classpath injection complete
23:57:23.256 [Lang/main] DEBUG: Found 4 translations
23:57:23.271 [Lang/main] INFO : Loaded translations 'cs_CZ'
23:57:23.276 [Lang/main] INFO : Loaded translations 'de_DE'
23:57:23.281 [Lang/main] INFO : Loaded translations 'en_US'
23:57:23.288 [Lang/main] INFO : Loaded translations 'zh_CN'
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/geometry/Pos
        at me.coley.recaf.config.container.EditorConfig.<init>(EditorConfig.java:46)
        at me.coley.recaf.config.Configs.<clinit>(Configs.java:15)
        at me.coley.recaf.presentation.GuiPresentation.initialize(GuiPresentation.java:41)
        at me.coley.recaf.Recaf.initialize(Recaf.java:38)
        at me.coley.recaf.Main.main(Main.java:44)
Caused by: java.lang.ClassNotFoundException: javafx.geometry.Pos
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Comment by Col-E** [comment]
3x currently has the same setup as 2x for fetching JFX classes, so refer to this issue: https://github.com/Col-E/Recaf/issues/604
