### ISSUE TITLE
Update RichTextFX to fix spam of "Visible paragraphs' last index is [-1]"

### ISSUE THREAD

**Issue by Col-E** [Col-E/recaf-3x-issues#24]
The bug is present in `10.6` but was fixed 2 months ago. When a new release is made it should fix the spam: https://github.com/FXMisc/RichTextFX/issues/1021

Full log
```
java.lang.IllegalArgumentException: Visible paragraphs' last index is [-1] but visibleParIndex was [0]
	at org.fxmisc.richtext.GenericStyledArea.visibleParToAllParIndex(GenericStyledArea.java:982)
	at org.fxmisc.richtext.ViewActions.firstVisibleParToAllParIndex(ViewActions.java:284)
	at org.fxmisc.richtext.LineNumberFactory.insertParagraphCheck(LineNumberFactory.java:172)
	at org.fxmisc.richtext.LineNumberFactory.lambda$new$2(LineNumberFactory.java:92)
```

**Comment by Col-E** [comment]
For SA, `0.10.7` depends on JFX logic introduced in a later version _(past the old 8 bundled version)_ so its effectively incompatible with Java 8 since we use the piece that is dependent. 

We planned on moving to Java 11 eventually anyways so this is not a major concern.
