### ISSUE TITLE
Allow assembler to modify class-level attributes

### ISSUE THREAD

**Issue by Col-E** [Col-E/recaf-3x-issues#63]
Could add a new rule for classes in the `bytecode.g4` which is could use `DEFINE-CLASS` instead of just `DEFINE` so the token is different.

From there it can support modifiers and annotations like a normal field/method assembler rule-set

**Comment by win32kbase** [comment]
At the moment, the assembler cannot even view annotations:
`java.lang.IllegalStateException: Unsupported argument type: org.objectweb.asm.tree.AnnotationNode`

**Comment by Col-E** [comment]
It was working before, where is that exception from?

**Comment by win32kbase** [comment]
```
21:49:44.590 [GuiPresentation:ERROR] Uncaught exception on thread 'JavaFX Application Thread'
java.lang.IllegalStateException: Unsupported argument type: org.objectweb.asm.tree.AnnotationNode
	at me.coley.recaf.assemble.ast.BaseArg.of(BaseArg.java:71)
	at me.coley.recaf.assemble.transformer.AnnotationHelper.lambda$visitAnnos$0(AnnotationHelper.java:51)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at me.coley.recaf.assemble.transformer.AnnotationHelper.visitAnnos(AnnotationHelper.java:52)
	at me.coley.recaf.assemble.transformer.BytecodeToAstTransformer.visitMethod(BytecodeToAstTransformer.java:165)
	at me.coley.recaf.assemble.transformer.BytecodeToAstTransformer.visit(BytecodeToAstTransformer.java:63)
	at me.coley.recaf.ui.control.code.bytecode.AssemblerArea.disassemble(AssemblerArea.java:177)
	at me.coley.recaf.ui.pane.assembler.AssemblerPane.onUpdate(AssemblerPane.java:163)
	at me.coley.recaf.ui.context.MethodContextBuilder.assemble(MethodContextBuilder.java:102)
	at me.coley.recaf.ui.control.menu.ActionMenuItem.lambda$new$1(ActionMenuItem.java:59)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
	at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3881)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:425)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
	at com.sun.glass.ui.View.notifyMouse(View.java:943)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Col-E** [comment]
Ah, JavaParser issue. Easy fix.

**Comment by Col-E** [comment]
This should have been closed a long time ago now that we're using https://github.com/Nowilltolife/Jasm
